DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE IF NOT EXISTS CUSTOMERS(
Customer_ID INT,
Age INT,
Gender VARCHAR(20),
Item_Purchased VARCHAR(30),
Category VARCHAR(20),
Purchase_Amount INT,
Location VARCHAR(50),
Size VARCHAR(10),
Color VARCHAR(10),
Season VARCHAR(20),
Review_Rating NUMERIC,
Subscription VARCHAR(20),
Shipping_Type VARCHAR(30),
Discount_Applied VARCHAR(10),
Promo_Code VARCHAR(10),
Previous_Purchases INT,
Payment_Method VARCHAR(20),
Frequency_of_Purchase VARCHAR(30)
);


COPY CUSTOMERS(Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount,Location,Size,Color,Season,Review_Rating,Subscription,Shipping_Type,Discount_Applied,Promo_Code,Previous_Purchases,Payment_Method,Frequency_of_Purchase)
FROM 'D:\MEHUL\SQL\PROJECTS\CLOTHES\customer_dataset_500rows.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM CUSTOMERS;

--Gender Wise Total Revenue
SELECT GENDER,SUM(PURCHASE_AMOUNT) AS REVENUE_BY_GENDER
FROM CUSTOMERS
GROUP BY GENDER
ORDER BY SUM(PURCHASE_AMOUNT) DESC

--SHOW CUSTOMERS WHOSE PURCHASE AMOUNT IS ABOVE THEN AVG
SELECT CUSTOMER_ID,DISCOUNT_APPLIED,PURCHASE_AMOUNT
FROM CUSTOMERS
WHERE DISCOUNT_APPLIED='Yes' AND PURCHASE_AMOUNT >=(SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMERS)

--SHOW TOP 5 HIGHEST RATED ITEMS
SELECT ITEM_PURCHASED, ROUND(AVG(REVIEW_RATING),2) AS AVG_RATING
FROM CUSTOMERS
GROUP BY ITEM_PURCHASED
ORDER BY AVG_RATING DESC LIMIT 5

--SHOW AVG PURCHASING AMOUNT BY SHIPPING TYPE
SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_AMOUNT
FROM CUSTOMERS
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE

--COUNT CUSTOMERS WHO HAS SUBSCRIPTION BUT LOW PURCHASE AMOUNT
SELECT Subscription,
COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_SPEND,
SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE FROM CUSTOMERS
GROUP BY Subscription
ORDER BY TOTAL_REVENUE,AVG_SPEND

--DISPLAY DISCOUNT RATE BY ITEM PURCHASED
SELECT ITEM_PURCHASED,
ROUND(100* SUM(CASE WHEN DISCOUNT_APPLIED='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS DISCOUNT_RATE
FROM CUSTOMERS
GROUP BY ITEM_PURCHASED
ORDER BY DISCOUNT_RATE DESC LIMIT 5 

--DISPLAY ACTIVLY BUYERS BY SUBSCRIPTION
SELECT SUBSCRIPTION,
COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMERS
WHERE PREVIOUS_PURCHASES>5
GROUP BY SUBSCRIPTION

--DISPLAY TOTAL REVENUE BY AGE GROUP
SELECT AGE, SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMERS 
GROUP BY AGE
ORDER BY TOTAL_REVENUE DESC